---
title: "STA 325 Case Study Test Predictions"
authors: "Grady P., Laura C., Abby L., Ava E., & Ella T."
output: html_document
---

The goal of this RMD is to predict the central moments for the hold out set using the final models.

```{r}
## Loading the libraries 
library(tidyverse)
library(dplyr)
library(glmnet)
library(readr)

## Loading the data
data <- read.csv("Data/data_transformed.csv")
data_test <- read.csv("Data/data-test.csv")
```

```{r}
# Transforming the test set
data_test <- data_test |>
  mutate(
         St_sqrt = sqrt(St),
         logistic_Fr = 1/(1+exp(-Fr)) # using logitistic transformation for inf
         )
```


## Mean

```{r}
# Building the mean model
model_mean_poly <- lm(log(mean) ~ poly(sqrt(St), 2) + 
                                poly(Re, 2) + 
                                poly(logistic_Fr, 2) +
                                sqrt(St):Re + 
                                sqrt(St):logistic_Fr + 
                                Re:logistic_Fr, 
                      data = data)

# Making predictions
mean_predict <- predict(model_mean_poly, data_test)

# Transforming back by exponentiating
mean_pred <- exp(mean_predict)

# Adding back to the final test data
data_test$mean <- mean_pred

```


## Standard Deviation

```{r}
# Fitting the standard deviation model
sd_fit <- lm(log(sd) ~ (log(St)+log(Re)+logistic_Fr)^2, data)

sd_predict <- predict(sd_fit, data_test)

# Un-logging the final values
sd_pred <- exp(sd_predict)

# Adding to the final data frame
data_test$sd <- sd_pred

```

## Skewness

```{r}
# Building the ridge model
set.seed(325)
y_train <- data$skewness
rhs_formula <- ~ St_sqrt + Re + logistic_Fr + St_sqrt:Re + 
               St_sqrt:logistic_Fr + Re:logistic_Fr

X_train <- model.matrix(rhs_formula, data = data)[, -1]

# Fitting the ridge model
ridge_fit_skew <- cv.glmnet(X_train, y_train, 
                            alpha = 0, nfolds = 5)
```

```{r}
# Getting the relevant columns
X_test  <- model.matrix(rhs_formula, data = data_test)[, -1]

# Predicting the skewness for the hold out set
y_pred_mat <- predict(ridge_fit_skew, newx = X_test, s = "lambda.min")
y_pred_skew <- as.numeric(y_pred_mat)

```

```{r}
# Binding to the test dataset
data_test$skewness <- y_pred_skew
```


## Kurtosis

```{r}
# Fitting the polynomial model
poly_kurt <- lm(log(kurtosis) ~ sqrt(St) + poly(Re, 2) + poly(logistic_Fr, 2) + 
                   sqrt(St):poly(Re,2) + sqrt(St):poly(logistic_Fr,2) + 
                   poly(Re,2):poly(logistic_Fr,2), data = data)

# Predicting on the model
kurt_predict <- predict(poly_kurt, data_test)

# Untransforming to get back to log
kurt_pred <- exp(kurt_predict)

```

```{r}
# Adding a column to the test dataset
data_test$kurtosis <- kurt_pred
```

## Final Edits
```{r}
# Just selecting the relevant columns
data_test <- data_test[, c("St", "Fr", "Re", "mean", "sd", "skewness", "kurtosis")]

```

```{r}
# Writing to CSV
write_csv(data_test, "Data/data-test-final.csv")
```



